/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatGrafico;


import javax.swing.JOptionPane;

/**
 *
 * @author rogerjoseulaterivera
 */
public class ClientUI extends javax.swing.JFrame {

    /*
    *   @author: custom instances
    */
    Backend backend = new Backend();
    
    /**
     * Creates new form clientGraphic
     */
    public ClientUI() {
        initComponents();
    }
    
    public boolean verificaNombreVacio() {
        
        /*
            Metodo verifica que no hayan campos vacios que puedan
            ser definidos como requeridos
        */
        
        // Vars
        boolean result = false;

        if (ipNumberTxtF.getText().isEmpty() && portNumberTxtF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llenar los campos requeridos.");
        } else {
            result = true;
            btn_send.setEnabled(true);
        }

        return result;
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        label_nombreDeChat = new javax.swing.JLabel();
        btn_send = new javax.swing.JButton();
        chatTxtArea = new javax.swing.JTextField();
        ipNumberTxtF = new javax.swing.JTextField();
        portNumberTxtF = new javax.swing.JTextField();
        ipUIMessage = new javax.swing.JLabel();
        portUIMessage = new javax.swing.JLabel();
        jrecommendedPort = new javax.swing.JLabel();
        btnVerIP = new javax.swing.JButton();
        jlbl_verIPLocal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label_nombreDeChat.setText("Chat Lammer: Cliente");
        jPanel1.add(label_nombreDeChat, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        btn_send.setText("Enviar");
        btn_send.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_sendMouseClicked(evt);
            }
        });
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });
        jPanel1.add(btn_send, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));
        jPanel1.add(chatTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 360, 70));

        ipNumberTxtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ipNumberTxtFActionPerformed(evt);
            }
        });
        jPanel1.add(ipNumberTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 120, -1));

        portNumberTxtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portNumberTxtFActionPerformed(evt);
            }
        });
        jPanel1.add(portNumberTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 90, -1));

        ipUIMessage.setText("Conectarse a la ip:");
        jPanel1.add(ipUIMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        portUIMessage.setText("Con el puerto:");
        jPanel1.add(portUIMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 20));

        jrecommendedPort.setText("Recomendado: 5432");
        jPanel1.add(jrecommendedPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        btnVerIP.setText("Ver IP Local");
        btnVerIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerIPActionPerformed(evt);
            }
        });
        jPanel1.add(btnVerIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 100, -1));
        jPanel1.add(jlbl_verIPLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 120, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed

        /*
        *   Boton de accion que realiza la conexion y envia tambien el mensaje
        *   al servidor al que se conecta
        */
        
        // Verifica que no hayan valores vacios requeridos
        if(verificaNombreVacio()){
            
            // Crear instancia para conectar y enviar mensaje
            backend.clientMessageAndConnection(ipNumberTxtF.getText(), portNumberTxtF.getText(), chatTxtArea.getText());
        
            // Limpiar texto del chat
            chatTxtArea.setText(null); 
            
        }
        
    }//GEN-LAST:event_btn_sendActionPerformed

    private void portNumberTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portNumberTxtFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_portNumberTxtFActionPerformed

    private void ipNumberTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ipNumberTxtFActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ipNumberTxtFActionPerformed

    private void btn_sendMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_sendMouseClicked
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_btn_sendMouseClicked

    private void btnVerIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerIPActionPerformed
        
        /*
        *   El boton obtiene la IP local donde se este ejecutando el programa en el momento
        */
        
        // Get local IP of LocalHost 
        jlbl_verIPLocal.setText(backend.getIpToClient());
        
        
    }//GEN-LAST:event_btnVerIPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ClientUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerIP;
    private javax.swing.JButton btn_send;
    private javax.swing.JTextField chatTxtArea;
    private javax.swing.JTextField ipNumberTxtF;
    private javax.swing.JLabel ipUIMessage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbl_verIPLocal;
    private javax.swing.JLabel jrecommendedPort;
    private javax.swing.JLabel label_nombreDeChat;
    private javax.swing.JTextField portNumberTxtF;
    private javax.swing.JLabel portUIMessage;
    // End of variables declaration//GEN-END:variables
}
