/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package chatGrafico;

import javax.swing.JOptionPane;

/**
 *
 * @author rogerjoseulaterivera
 */
public class ServerUI extends javax.swing.JFrame {

    /*
    *   @author: custom instances
    */
    Backend backend = new Backend();
    
    /**
     * Creates new form clientGraphic
     */
    public ServerUI() {
        initComponents();
        // devuelve el mensaje del cliente al servidor
        backend.getClienteMessageToServer();
    }
    
    public boolean verificaNombreVacio() {
        
        /*
            Metodo verifica que no hayan campos vacios que puedan
            ser definidos como requeridos
        */
        
        // Vars
        boolean result = false;

        if (portNumberTxtF.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor llenar los campos requeridos.");
        } else {
            result = true;
            jYesOnServer.setEnabled(true);
        }

        return result;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        chatTxtArea = new javax.swing.JTextField();
        ipUIMessage = new javax.swing.JLabel();
        jYesOnServer = new javax.swing.JButton();
        btnVerIP = new javax.swing.JButton();
        jlbl_verIPLocal = new javax.swing.JLabel();
        portUIMessage = new javax.swing.JLabel();
        portNumberTxtF = new javax.swing.JTextField();
        jrecommendedPort = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText("Chat Lammer: Servidor");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));

        chatTxtArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chatTxtAreaActionPerformed(evt);
            }
        });
        getContentPane().add(chatTxtArea, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 360, 90));

        ipUIMessage.setText("Encender servidor:");
        getContentPane().add(ipUIMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        jYesOnServer.setText("Si");
        jYesOnServer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYesOnServerActionPerformed(evt);
            }
        });
        getContentPane().add(jYesOnServer, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 140, -1, -1));

        btnVerIP.setText("Ver IP Local");
        btnVerIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerIPActionPerformed(evt);
            }
        });
        getContentPane().add(btnVerIP, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 100, -1));
        getContentPane().add(jlbl_verIPLocal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 120, 20));

        portUIMessage.setText("Con el puerto:");
        getContentPane().add(portUIMessage, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, 20));

        portNumberTxtF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portNumberTxtFActionPerformed(evt);
            }
        });
        getContentPane().add(portNumberTxtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 100, 90, -1));

        jrecommendedPort.setText("Recomendado: 5432");
        getContentPane().add(jrecommendedPort, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jYesOnServerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYesOnServerActionPerformed

        backend.serverMessageConnectionReceiver(Integer.parseInt(portNumberTxtF.getText()));
        chatTxtArea.setText(backend.getClienteMessageToServer());
        
    }//GEN-LAST:event_jYesOnServerActionPerformed

    private void btnVerIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerIPActionPerformed

        /*
        *   El boton obtiene la IP local donde se este ejecutando el programa en el momento
        */

        // Get local IP of LocalHost
        jlbl_verIPLocal.setText(backend.getIpToClient());

    }//GEN-LAST:event_btnVerIPActionPerformed

    private void portNumberTxtFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portNumberTxtFActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_portNumberTxtFActionPerformed

    private void chatTxtAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chatTxtAreaActionPerformed
        
        
    }//GEN-LAST:event_chatTxtAreaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServerUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServerUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVerIP;
    private javax.swing.JTextField chatTxtArea;
    private javax.swing.JLabel ipUIMessage;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton jYesOnServer;
    private javax.swing.JLabel jlbl_verIPLocal;
    private javax.swing.JLabel jrecommendedPort;
    private javax.swing.JTextField portNumberTxtF;
    private javax.swing.JLabel portUIMessage;
    // End of variables declaration//GEN-END:variables
}
