/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller01;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author roger
 */
public class MenuApp extends javax.swing.JFrame {

    public static ArrayList<Profesor> listadoProfesores = new ArrayList<Profesor>();
    ProfesorTitular profeFijo;
    ProfesorInterino profeNoFijo;

    
    /**
     * Creates new form MenuApp
     */
    public MenuApp() {
        initComponents();
    }
    
    public boolean verificaDatosVacio() {
        
        /*
            Metodo verifica que no hayan campos vacios que puedan
            ser definidos como requeridos
        */
        
        // Vars
        boolean result;

        if (jTextApellido.getText().isEmpty() || 
            jTextNombre.getText().isEmpty() ||
            jTextEdad.getText().isEmpty() ||
            jTextCedula.getText().isEmpty() ||
            jTextCantClases.getText().isEmpty() ||
            jTextFechaComienzoAnio.getText().isEmpty() ||
            jTextFechaComienzoDia.getText().isEmpty() ||
            jTextFechaComienzoMes.getText().isEmpty()
            ) {
            result = false;
        } else {
            result = true;
            btn_profInterino.setEnabled(true);
            btn_profTitular.setEnabled(true);
        }

        return result;
        
    }
    
    public boolean verificarLongitudFechaComienzo(){
        
        boolean result = false;
        int anio = jTextFechaComienzoAnio.getText().length();
        int dia = jTextFechaComienzoDia.getText().length();
        int mes = jTextFechaComienzoMes.getText().length();
        
        if(anio == 4 && dia == 2 && mes == 2){
            result = true;
        }
        
        return result;
        
    }
    
    public boolean verificarLongitudFechaFinal(){
    
        boolean result = false;
        int anio = jTextFechaFinalAnio.getText().length();
        int dia = jTextFechaFinalDia.getText().length();
        int mes = jTextFechaFinalMes.getText().length();
        
        if(anio == 4 && dia == 2 && mes == 2){
            result = true;
        }
        
        return result;
        
    }
    
    public boolean verificarCantidadLecciones(){
        
        boolean resultado = false;
        
        int cantidadClases = Integer.parseInt(jTextCantClases.getText());
        
        if(cantidadClases >= 40 && cantidadClases <= 48){
            resultado = true;
        }else{
            JOptionPane.showMessageDialog(null, "La cantidad de clases debe ser en un rango de 40 a 48 clases", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        return resultado;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLNombre = new javax.swing.JLabel();
        jLTitle = new javax.swing.JLabel();
        jLApellido = new javax.swing.JLabel();
        jLEdad = new javax.swing.JLabel();
        jLCedula = new javax.swing.JLabel();
        jLCantClases = new javax.swing.JLabel();
        jLFechaComienzo = new javax.swing.JLabel();
        jLFechaFinal = new javax.swing.JLabel();
        btn_profTitular = new javax.swing.JButton();
        jTextNombre = new javax.swing.JTextField();
        jTextApellido = new javax.swing.JTextField();
        jTextEdad = new javax.swing.JTextField();
        jTextCedula = new javax.swing.JTextField();
        jTextCantClases = new javax.swing.JTextField();
        jTextFechaComienzoDia = new javax.swing.JTextField();
        jTextFechaFinalDia = new javax.swing.JTextField();
        jTextFechaComienzoMes = new javax.swing.JTextField();
        jTextFechaComienzoAnio = new javax.swing.JTextField();
        jTextFechaFinalMes = new javax.swing.JTextField();
        jTextFechaFinalAnio = new javax.swing.JTextField();
        btn_profInterino = new javax.swing.JButton();
        btn_mostrarProfesores = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextAreaMostrarDatos = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLNombre.setText("Nombre:");

        jLTitle.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLTitle.setText("TALLER 1");

        jLApellido.setText("Apellido:");

        jLEdad.setText("Edad:");

        jLCedula.setText("Cedula:");

        jLCantClases.setText("Cantidad de clases:");

        jLFechaComienzo.setText("Fecha Comienzo");

        jLFechaFinal.setText("Fecha Final (solo Interino):");

        btn_profTitular.setText("Agregar Profesor Titular");
        btn_profTitular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profTitularActionPerformed(evt);
            }
        });

        jTextFechaComienzoMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaComienzoMesActionPerformed(evt);
            }
        });

        jTextFechaComienzoAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFechaComienzoAnioActionPerformed(evt);
            }
        });

        btn_profInterino.setText("Agregar Profesor Interino");
        btn_profInterino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_profInterinoActionPerformed(evt);
            }
        });

        btn_mostrarProfesores.setText("Mostrar profesores");
        btn_mostrarProfesores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mostrarProfesoresActionPerformed(evt);
            }
        });

        jTextAreaMostrarDatos.setEditable(false);
        jTextAreaMostrarDatos.setColumns(20);
        jTextAreaMostrarDatos.setRows(5);
        jScrollPane2.setViewportView(jTextAreaMostrarDatos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_profTitular)
                        .addGap(31, 31, 31)
                        .addComponent(btn_profInterino)
                        .addGap(18, 18, 18)
                        .addComponent(btn_mostrarProfesores))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTitle)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLFechaFinal, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLFechaComienzo, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLCantClases, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLCedula, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLEdad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLApellido, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLNombre, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextApellido)
                                    .addComponent(jTextEdad, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCedula, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextCantClases, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFechaComienzoDia, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                                            .addComponent(jTextFechaFinalDia))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextFechaComienzoMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFechaFinalMes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFechaComienzoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFechaFinalAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jTextNombre))))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLTitle)
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLNombre))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLApellido))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLEdad))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCedula))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextCantClases, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLCantClases))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFechaComienzoDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFechaComienzo)
                            .addComponent(jTextFechaComienzoMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFechaComienzoAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFechaFinalDia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLFechaFinal)
                            .addComponent(jTextFechaFinalMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFechaFinalAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 404, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_profTitular)
                    .addComponent(btn_profInterino)
                    .addComponent(btn_mostrarProfesores))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFechaComienzoMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaComienzoMesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaComienzoMesActionPerformed

    private void jTextFechaComienzoAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFechaComienzoAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFechaComienzoAnioActionPerformed

    private void btn_profTitularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profTitularActionPerformed

        String fechaComienzo;
        
        if(verificaDatosVacio() && verificarLongitudFechaComienzo() && verificarCantidadLecciones()){
            try{
                
                fechaComienzo = jTextFechaComienzoDia.getText() + "/" + jTextFechaComienzoMes.getText() + "/" + jTextFechaComienzoAnio.getText();

                /*
                listadoProfesores.add(new ProfesorTitular(jTextNombre.getText(), 
                                            jTextApellido.getText(),
                                            Integer.parseInt(jTextEdad.getText()),
                                            Integer.parseInt(jTextCedula.getText()),
                                            Float.parseFloat(jTextSalario.getText()),
                                            Integer.parseInt(jTextCantClases.getText()),
                                            fechaComienzo));
                */
                
                profeFijo = new ProfesorTitular(jTextNombre.getText(), 
                                                jTextApellido.getText(),
                                                Integer.parseInt(jTextEdad.getText()),
                                                Integer.parseInt(jTextCedula.getText()),
                                                Integer.parseInt(jTextCantClases.getText()),
                                                fechaComienzo);
                
                profeFijo.calcularSalario();
                
                listadoProfesores.add(profeFijo);
                
                System.out.println("Profesor agregado");
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "No se puede procesar informacion,\tuno de los datos numericos no es numerico,\trevise por favor", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Campo sin informacion, revisar: Nombre,\nApellido,\nEdad,\nCedula,\nSalario,\nCantidad de Clases\nFecha Comienzo: Dia,\nFecha Comienzo: Mes,\nFecha Comienzo: Año.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        jTextApellido.setText(null);
        jTextCantClases.setText(null);
        jTextCedula.setText(null);
        jTextEdad.setText(null);
        jTextFechaComienzoAnio.setText(null);
        jTextFechaComienzoDia.setText(null);
        jTextFechaComienzoMes.setText(null);
        jTextFechaFinalAnio.setText(null);
        jTextFechaFinalDia.setText(null);
        jTextFechaFinalMes.setText(null);
        jTextNombre.setText(null);
        
    }//GEN-LAST:event_btn_profTitularActionPerformed

    private void btn_profInterinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_profInterinoActionPerformed
        
        String fechaComienzo;
        String fechaFinal;
        
        if(verificaDatosVacio() && verificarLongitudFechaComienzo() && verificarLongitudFechaFinal() && verificarCantidadLecciones()){
            try{
                
                fechaComienzo = jTextFechaComienzoDia.getText() + "/" + jTextFechaComienzoMes.getText() + "/" + jTextFechaComienzoAnio.getText();
                fechaFinal = jTextFechaFinalDia.getText() + "/" + jTextFechaFinalMes.getText() + "/" + jTextFechaFinalAnio.getText();

                listadoProfesores.add(new ProfesorInterino(jTextNombre.getText(), 
                                            jTextApellido.getText(),
                                            Integer.parseInt(jTextEdad.getText()),
                                            Integer.parseInt(jTextCedula.getText()),
                                            Integer.parseInt(jTextCantClases.getText()),
                                            fechaComienzo,
                                            fechaFinal));
                
                
                System.out.println("Profesor agregado");
                
                
                
            }catch(Exception ex){
                JOptionPane.showMessageDialog(null, "No se puede procesar informacion,\tuno de los datos numericos no es numerico,\trevise por favor", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Campo sin informacion, revisar: Nombre,\nApellido,\nEdad,\nCedula,\nSalario,\nCantidad de Clases\nFecha Comienzo: Dia,\nFecha Comienzo: Mes,\nFecha Final: Año,\nFecha Final: Mes,\nFecha Final: Año.\nO bien las fechas no son DD/MM/YYYY de longitud", "Error", JOptionPane.ERROR_MESSAGE);
        }
        
        jTextApellido.setText(null);
        jTextCantClases.setText(null);
        jTextCedula.setText(null);
        jTextEdad.setText(null);
        jTextFechaComienzoAnio.setText(null);
        jTextFechaComienzoDia.setText(null);
        jTextFechaComienzoMes.setText(null);
        jTextFechaFinalAnio.setText(null);
        jTextFechaFinalDia.setText(null);
        jTextFechaFinalMes.setText(null);
        jTextNombre.setText(null);
        
    }//GEN-LAST:event_btn_profInterinoActionPerformed

    private void btn_mostrarProfesoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mostrarProfesoresActionPerformed
        
        jTextAreaMostrarDatos.append("" + listadoProfesores.clone());
        
    }//GEN-LAST:event_btn_mostrarProfesoresActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuApp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuApp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_mostrarProfesores;
    private javax.swing.JButton btn_profInterino;
    private javax.swing.JButton btn_profTitular;
    private javax.swing.JLabel jLApellido;
    private javax.swing.JLabel jLCantClases;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLEdad;
    private javax.swing.JLabel jLFechaComienzo;
    private javax.swing.JLabel jLFechaFinal;
    private javax.swing.JLabel jLNombre;
    private javax.swing.JLabel jLTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextApellido;
    private javax.swing.JTextArea jTextAreaMostrarDatos;
    private javax.swing.JTextField jTextCantClases;
    private javax.swing.JTextField jTextCedula;
    private javax.swing.JTextField jTextEdad;
    private javax.swing.JTextField jTextFechaComienzoAnio;
    private javax.swing.JTextField jTextFechaComienzoDia;
    private javax.swing.JTextField jTextFechaComienzoMes;
    private javax.swing.JTextField jTextFechaFinalAnio;
    private javax.swing.JTextField jTextFechaFinalDia;
    private javax.swing.JTextField jTextFechaFinalMes;
    private javax.swing.JTextField jTextNombre;
    // End of variables declaration//GEN-END:variables
}
