//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ComercioEntities : DbContext
    {
        public ComercioEntities()
            : base("name=ComercioEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Bitacora> Bitacora { get; set; }
        public virtual DbSet<Canton> Canton { get; set; }
        public virtual DbSet<Consecutivos> Consecutivos { get; set; }
        public virtual DbSet<Detalle_Factura> Detalle_Factura { get; set; }
        public virtual DbSet<Detalle_Pedido> Detalle_Pedido { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Errores> Errores { get; set; }
        public virtual DbSet<Facturas> Facturas { get; set; }
        public virtual DbSet<Lineas> Lineas { get; set; }
        public virtual DbSet<Pedidos> Pedidos { get; set; }
        public virtual DbSet<Privilegios> Privilegios { get; set; }
        public virtual DbSet<Privilegios_Usuarios> Privilegios_Usuarios { get; set; }
        public virtual DbSet<Productos> Productos { get; set; }
        public virtual DbSet<Proveedores> Proveedores { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tipo_Consecutivo> Tipo_Consecutivo { get; set; }
        public virtual DbSet<Usuarios> Usuarios { get; set; }
    }
}
