package companyjdr;

import javax.swing.JOptionPane;
import clases.*;

public class AgregarPaquetes extends javax.swing.JFrame {

    MenuClases mc = new MenuClases();
    Main menu = new Main();
    // Arbol arbolDuracionVuelo;

    /**
     * Creates new form AgregarPaquetes
     */
    public AgregarPaquetes() {
        initComponents();
        this.setLocationRelativeTo(null);
        //arbolDuracionVuelo = new Arbol();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        destinoPaqueteLbl = new javax.swing.JLabel();
        destinoNuevoPaqueteTxt = new javax.swing.JTextField();
        informacionDelViajeLbl = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        informacionPaqueteTxt = new javax.swing.JTextArea();
        agregarPaqueteBtn = new javax.swing.JButton();
        volverBtn = new javax.swing.JButton();
        duracionPaqueteCbx = new javax.swing.JComboBox<>();
        duracionVuelolbl = new javax.swing.JLabel();
        horasLbl = new javax.swing.JLabel();
        fondoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        destinoPaqueteLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        destinoPaqueteLbl.setForeground(new java.awt.Color(255, 255, 255));
        destinoPaqueteLbl.setText("Ingrese el nuevo paquete de viaje:");
        getContentPane().add(destinoPaqueteLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, -1, -1));

        destinoNuevoPaqueteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoNuevoPaqueteTxtActionPerformed(evt);
            }
        });
        getContentPane().add(destinoNuevoPaqueteTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 60, 230, 30));

        informacionDelViajeLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        informacionDelViajeLbl.setForeground(new java.awt.Color(255, 255, 255));
        informacionDelViajeLbl.setText("Información sobre el viaje:");
        getContentPane().add(informacionDelViajeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, -1, -1));

        informacionPaqueteTxt.setColumns(20);
        informacionPaqueteTxt.setRows(5);
        jScrollPane2.setViewportView(informacionPaqueteTxt);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 140, 230, 150));

        agregarPaqueteBtn.setBackground(new java.awt.Color(255, 102, 51));
        agregarPaqueteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregarPaqueteBtn.setForeground(new java.awt.Color(240, 240, 240));
        agregarPaqueteBtn.setText("Agregar el nuevo paquete");
        agregarPaqueteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPaqueteBtnActionPerformed(evt);
            }
        });
        getContentPane().add(agregarPaqueteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 460, -1, 30));

        volverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton atras.png"))); // NOI18N
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 60, 50));

        duracionPaqueteCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "0", "1", "2 ", "3", "4", "5", "6", "7", "8", "9", "10" }));
        duracionPaqueteCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionPaqueteCbxActionPerformed(evt);
            }
        });
        getContentPane().add(duracionPaqueteCbx, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, 50, -1));

        duracionVuelolbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        duracionVuelolbl.setForeground(new java.awt.Color(240, 240, 240));
        duracionVuelolbl.setText("Duracion del vuelo");
        getContentPane().add(duracionVuelolbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 190, -1));

        horasLbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        horasLbl.setForeground(new java.awt.Color(240, 240, 240));
        horasLbl.setText("Horas");
        getContentPane().add(horasLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, -1, -1));

        fondoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo avion company2.jpg"))); // NOI18N
        fondoLbl.setText("jLabel1");
        getContentPane().add(fondoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 592, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarPaqueteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPaqueteBtnActionPerformed
        // TODO add your handling code here:
        if (infoPaquete()) {

            // Recibimos un arbol
            // Arbol arbolDuracionVuelo = new Arbol();
            // mc.agregarPaqueteLista(new Paquete(destinoNuevoPaqueteTxt.getText(), informacionPaqueteTxt.getText(), camposVendidosCbx.getSelectedIndex(), arbolDuracionVuelo, aviones));
            mc.agregarPaqueteLista(new Paquete(destinoNuevoPaqueteTxt.getText(), informacionPaqueteTxt.getText(), duracionPaqueteCbx.getSelectedIndex()));
            //mc.insertarHorasAlArbol(new NodoArbol(camposVendidosCbx.getSelectedIndex()));
            mc.insertaDuracionAArbol(duracionPaqueteCbx.getSelectedIndex());
            
            
            menu.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_agregarPaqueteBtnActionPerformed

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        //boton que retorna a la pantalla principal
        Main inicio = new Main();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    private void duracionPaqueteCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionPaqueteCbxActionPerformed


    }//GEN-LAST:event_duracionPaqueteCbxActionPerformed

    private void destinoNuevoPaqueteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoNuevoPaqueteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_destinoNuevoPaqueteTxtActionPerformed

    public boolean infoPaquete() {
        //metodo utilizado para que el usuario no guarde o modifique datos sin rellenar los campos necesarios 
        boolean result = false;//se crea un boolean y se iguala a false

        if (destinoNuevoPaqueteTxt.getText().isEmpty() || informacionPaqueteTxt.getText().isEmpty()) {//if que revisa que los textfields de destino e informacion de paquete esten llenos
            JOptionPane.showMessageDialog(null, "Por favor no dejar campos sin rellenar");//si no estan llenos los campos envia una ventana de dialogo JOptionPane que le dira que relene los campos
        } else {
            result = true;//se retorna true 
        }

        return result;//retorna el resultado 
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarPaquetes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarPaquetes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton agregarPaqueteBtn;
    private javax.swing.JTextField destinoNuevoPaqueteTxt;
    private javax.swing.JLabel destinoPaqueteLbl;
    private javax.swing.JComboBox<String> duracionPaqueteCbx;
    private javax.swing.JLabel duracionVuelolbl;
    private javax.swing.JLabel fondoLbl;
    private javax.swing.JLabel horasLbl;
    private javax.swing.JLabel informacionDelViajeLbl;
    private javax.swing.JTextArea informacionPaqueteTxt;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
