package companyjdr;

import clases.*;

public class Main extends javax.swing.JFrame {

    // Declarar clases externas
    MenuClases menuClases;
    static Pila pilaClientes = new Pila();
    static Lista listaPaquetes = new Lista();

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        // Inicializar clases externas
        menuClases = new MenuClases();
        // Test
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        agregarPaqueteBtn = new javax.swing.JButton();
        verPaqueteBtn = new javax.swing.JButton();
        agregarPasajeroBtn = new javax.swing.JButton();
        salirBtn = new javax.swing.JButton();
        buscarPasajeroBtn = new javax.swing.JButton();
        BuscaPorDuracionBtn = new javax.swing.JButton();
        mostrarPasajerosBtn = new javax.swing.JButton();
        buscarPaquetesBtn = new javax.swing.JButton();
        fondoLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        agregarPaqueteBtn.setBackground(new java.awt.Color(255, 102, 51));
        agregarPaqueteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregarPaqueteBtn.setForeground(new java.awt.Color(240, 240, 240));
        agregarPaqueteBtn.setText("Agregar Paquetes");
        agregarPaqueteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPaqueteBtnActionPerformed(evt);
            }
        });
        panel.add(agregarPaqueteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 190, 40));

        verPaqueteBtn.setBackground(new java.awt.Color(255, 102, 51));
        verPaqueteBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        verPaqueteBtn.setForeground(new java.awt.Color(240, 240, 240));
        verPaqueteBtn.setText("Ver  Paquetes");
        verPaqueteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verPaqueteBtnActionPerformed(evt);
            }
        });
        panel.add(verPaqueteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 190, 40));

        agregarPasajeroBtn.setBackground(new java.awt.Color(255, 102, 51));
        agregarPasajeroBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        agregarPasajeroBtn.setForeground(new java.awt.Color(240, 240, 240));
        agregarPasajeroBtn.setText("Agregar Pasajeros");
        agregarPasajeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarPasajeroBtnActionPerformed(evt);
            }
        });
        panel.add(agregarPasajeroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 190, 40));

        salirBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Boton Salir.png"))); // NOI18N
        salirBtn.setToolTipText("");
        salirBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirBtnActionPerformed(evt);
            }
        });
        panel.add(salirBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 70, 70));

        buscarPasajeroBtn.setBackground(new java.awt.Color(255, 102, 51));
        buscarPasajeroBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscarPasajeroBtn.setForeground(new java.awt.Color(240, 240, 240));
        buscarPasajeroBtn.setText("Buscar Pasajero");
        buscarPasajeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPasajeroBtnActionPerformed(evt);
            }
        });
        panel.add(buscarPasajeroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 190, 40));

        BuscaPorDuracionBtn.setBackground(new java.awt.Color(255, 102, 51));
        BuscaPorDuracionBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BuscaPorDuracionBtn.setForeground(new java.awt.Color(240, 240, 240));
        BuscaPorDuracionBtn.setText("Busca Duracion Vuelos");
        BuscaPorDuracionBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BuscaPorDuracionBtnActionPerformed(evt);
            }
        });
        panel.add(BuscaPorDuracionBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 40));

        mostrarPasajerosBtn.setBackground(new java.awt.Color(255, 102, 51));
        mostrarPasajerosBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        mostrarPasajerosBtn.setForeground(new java.awt.Color(240, 240, 240));
        mostrarPasajerosBtn.setText("Mostrar Pasajeros");
        mostrarPasajerosBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrarPasajerosBtnActionPerformed(evt);
            }
        });
        panel.add(mostrarPasajerosBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 190, 40));

        buscarPaquetesBtn.setBackground(new java.awt.Color(255, 102, 51));
        buscarPaquetesBtn.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buscarPaquetesBtn.setForeground(new java.awt.Color(240, 240, 240));
        buscarPaquetesBtn.setText("Buscar Paquetes");
        buscarPaquetesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarPaquetesBtnActionPerformed(evt);
            }
        });
        panel.add(buscarPaquetesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, 40));

        fondoLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logo avion company2.jpg"))); // NOI18N
        fondoLbl.setText("fondoLbl");
        panel.add(fondoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 591, 520));

        getContentPane().add(panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // Boton para ingresar a ventana de agregar un paquete
    private void agregarPaqueteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPaqueteBtnActionPerformed
        AgregarPaquetes addPaquete = new AgregarPaquetes();
        addPaquete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarPaqueteBtnActionPerformed

    // Boton para ingresar a ventana de ver paquetes
    private void verPaqueteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verPaqueteBtnActionPerformed
        VerPaquetesViaje paqueteViaje = new VerPaquetesViaje();
        paqueteViaje.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_verPaqueteBtnActionPerformed

    // Boton para ingresar a ventana de agregar un pasajero
    private void agregarPasajeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarPasajeroBtnActionPerformed
        AgregarPasajeros pasajero = new AgregarPasajeros();
        pasajero.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_agregarPasajeroBtnActionPerformed

    // Boton para salir de la ventana principal
    private void salirBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirBtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirBtnActionPerformed

    private void buscarPasajeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPasajeroBtnActionPerformed
        // TODO add your handling code here:
        BuscarPasajero buscar = new BuscarPasajero();
        buscar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarPasajeroBtnActionPerformed

    private void BuscaPorDuracionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BuscaPorDuracionBtnActionPerformed
        BuscaPorDuracion buscaDuracion = new BuscaPorDuracion();
        buscaDuracion.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_BuscaPorDuracionBtnActionPerformed

    private void mostrarPasajerosBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrarPasajerosBtnActionPerformed
        MuestraTodosPasajeros mostrarTodos = new MuestraTodosPasajeros();
        mostrarTodos.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_mostrarPasajerosBtnActionPerformed

    private void buscarPaquetesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarPaquetesBtnActionPerformed
        BuscarPaquete buscaPaquete = new BuscarPaquete();
        buscaPaquete.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_buscarPaquetesBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BuscaPorDuracionBtn;
    private javax.swing.JButton agregarPaqueteBtn;
    private javax.swing.JButton agregarPasajeroBtn;
    private javax.swing.JButton buscarPaquetesBtn;
    private javax.swing.JButton buscarPasajeroBtn;
    private javax.swing.JLabel fondoLbl;
    private javax.swing.JButton mostrarPasajerosBtn;
    private javax.swing.JPanel panel;
    private javax.swing.JButton salirBtn;
    private javax.swing.JButton verPaqueteBtn;
    // End of variables declaration//GEN-END:variables

}
