package companyjdr;
import javax.swing.*;
import clases.MenuClases;

public class VerPaquetesViaje extends javax.swing.JFrame {

    // Instancias
    MenuClases mc = new MenuClases();
    Main menu = new Main();
    
    /**
     * Creates new form VerPaquetesViaje
     */
    public VerPaquetesViaje() {
        initComponents();
        this.setLocationRelativeTo(null);
        visualizadatos();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paquetesDisponiblesLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        paquetesDisponiblesTxtArea = new javax.swing.JTextArea();
        volverBtn = new javax.swing.JButton();
        panelLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        paquetesDisponiblesLbl.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        paquetesDisponiblesLbl.setForeground(new java.awt.Color(255, 255, 255));
        paquetesDisponiblesLbl.setText("Paquetes Disponibles:");
        getContentPane().add(paquetesDisponiblesLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        paquetesDisponiblesTxtArea.setBackground(new java.awt.Color(255, 255, 204));
        paquetesDisponiblesTxtArea.setColumns(20);
        paquetesDisponiblesTxtArea.setRows(5);
        paquetesDisponiblesTxtArea.setEditable(false);
        jScrollPane1.setViewportView(paquetesDisponiblesTxtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 570, 340));

        volverBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/boton atras.png"))); // NOI18N
        volverBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverBtnActionPerformed(evt);
            }
        });
        getContentPane().add(volverBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 470, 60, 50));

        panelLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/fondo liso.jpg"))); // NOI18N
        getContentPane().add(panelLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverBtnActionPerformed
        Main inicio = new Main();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_volverBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerPaquetesViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerPaquetesViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerPaquetesViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerPaquetesViaje.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerPaquetesViaje().setVisible(true);
            }
        });
    }
    
    public void visualizadatos() {
        //llamamos la información y la pegamos en el textArea
        paquetesDisponiblesTxtArea.setText(mc.devuelveListaPaquetesCompleta().toString());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel panelLbl;
    private javax.swing.JLabel paquetesDisponiblesLbl;
    private javax.swing.JTextArea paquetesDisponiblesTxtArea;
    private javax.swing.JButton volverBtn;
    // End of variables declaration//GEN-END:variables
}
