//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Week08.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public int Cod_Producto { get; set; }
        public string Nombre_Producto { get; set; }
        public Nullable<int> Cod_Linea { get; set; }
        public Nullable<int> Cod_Proveedor { get; set; }
        public bool Descontinuado { get; set; }
    }
}
