/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package taller02;

import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.IOException;
import java.net.InetAddress;
import java.net.Socket;
import java.net.UnknownHostException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author roger
 */
public class ServidorCompeticion extends javax.swing.JFrame {

    // ATRIBUTOS, DECLARACIONES E INSTANCIAS
    int cantidadTirosCompetencia = 10;
    String[] listaNombresCompetidores;
    //private static final String ip = "127.0.0.1";
    private static final int port = 5432;
    ArrayList<Resultado> listaResultadosCompetidor = new ArrayList<Resultado>();
    
    Backend backend = new Backend();
    
    /**
     * Creates new form ClienteCompeticion
     */
    public ServidorCompeticion() {
        initComponents();
        backend.getClienteMessageToServer();
    }

    public void mostrar() {// refresh de la tabla cada vez que sea grega uno nuevo

        String matris[][] = new String[listaResultadosCompetidor.size()][4];
        for (int i = 0; i < listaResultadosCompetidor.size(); i++) {

            matris[i][0] = listaResultadosCompetidor.get(i).getNombre();
            matris[i][1] = listaResultadosCompetidor.get(i).getPromedioApunte();
            matris[i][2] = listaResultadosCompetidor.get(i).getPromedioDisparo();
            matris[i][3] = listaResultadosCompetidor.get(i).getPuntajeTotal();
        }

        jT_tablaCompeticion.setModel(new javax.swing.table.DefaultTableModel( // para que se muestre mi tbala
                matris,
                new String[]{
                    "Nombre Competidor", "Promedio Apunte", "Promedio Disparo", "Puntaje Total"
                }
        ));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_tablaCompeticion = new javax.swing.JTable();
        JBtn_encender = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 540, 73));

        jT_tablaCompeticion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nombre Competidor", "Promedio Apunte", "Promedio Disparo", "Puntuacion Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jT_tablaCompeticion);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 540, 430));

        JBtn_encender.setText("Encender");
        JBtn_encender.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JBtn_encenderMouseClicked(evt);
            }
        });
        jPanel1.add(JBtn_encender, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 580, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JBtn_encenderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_JBtn_encenderMouseClicked
        
        backend.serverMessageConnectionReceiver(port);
        
        String uno = backend.getClienteMessageToServer();
        String dos = backend.getClienteMessageToServer();
        String tres = backend.getClienteMessageToServer();
        String cuatro = backend.getClienteMessageToServer();
        
        Resultado resultado = new Resultado(uno, dos, tres, cuatro);
        
        listaResultadosCompetidor.add(resultado);
        
        mostrar();

    }//GEN-LAST:event_JBtn_encenderMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ServidorCompeticion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ServidorCompeticion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ServidorCompeticion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ServidorCompeticion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ServidorCompeticion().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBtn_encender;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jT_tablaCompeticion;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
