/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import ws.LoginWS;
import ws.LoginWS_Service;

/**
 *
 * @author roger
 */
public class Login extends javax.swing.JFrame {

    // Generar el anclaje de la conexion
    LoginWS_Service loginWS = new LoginWS_Service();
    // llamar a la interfaz de ese Web Service creado
    LoginWS login;
    
    
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        
        // En el constructor (este) instanciar al WebService
        // Instanciar el objeto que nos permite llamar a la interfaz
        // para obtener los metodos
        login = loginWS.getLoginWSPort();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jbl_welcome = new javax.swing.JLabel();
        jbl_welcome_description = new javax.swing.JLabel();
        jbl_user = new javax.swing.JLabel();
        jbl_password = new javax.swing.JLabel();
        jTxt_user = new javax.swing.JTextField();
        jTxt_password = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jbl_welcome.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jbl_welcome.setText("Bienvenido a SCVS");
        jPanel2.add(jbl_welcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jbl_welcome_description.setText("Sistema de Control de Venta Simple");
        jPanel2.add(jbl_welcome_description, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, -1, -1));

        jbl_user.setText("Usuario:");
        jPanel2.add(jbl_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 150, -1, -1));

        jbl_password.setText("Contraseña:");
        jPanel2.add(jbl_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));
        jPanel2.add(jTxt_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 140, -1));
        jPanel2.add(jTxt_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 140, -1));

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        
        String usuario = jTxt_user.getText();
        String contrasenia = jTxt_password.getText();
        
        String [] resultados = login.mainLogin(usuario, contrasenia);
        
    }//GEN-LAST:event_btn_ingresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTxt_password;
    private javax.swing.JTextField jTxt_user;
    private javax.swing.JLabel jbl_password;
    private javax.swing.JLabel jbl_user;
    private javax.swing.JLabel jbl_welcome;
    private javax.swing.JLabel jbl_welcome_description;
    // End of variables declaration//GEN-END:variables
}
