//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboratorio2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public int Cod_Distrito { get; set; }
        public string Nombre { get; set; }
        public string Codigo_Postal { get; set; }
        public Nullable<int> Cod_Canton { get; set; }
    
        public virtual Canton Canton { get; set; }
    }
}
