/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoConcurrente;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;


public class CalificacionProducto extends javax.swing.JInternalFrame {

    public CalificacionProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTxtItem = new javax.swing.JTextField();
        labelCompania = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        labelItem = new javax.swing.JLabel();
        jComboBoxCompania = new javax.swing.JComboBox();
        jComboBoxTipo = new javax.swing.JComboBox();
        labelPrecioPieza = new javax.swing.JLabel();
        jTxtPrecioPieza = new javax.swing.JTextField();
        labelCantidad = new javax.swing.JLabel();
        jTxtCantidad = new javax.swing.JTextField();
        labelTipo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Precio Productos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTxtItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtItemActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtItem);
        jTxtItem.setBounds(140, 20, 150, 30);

        labelCompania.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCompania.setText("Compañía");
        getContentPane().add(labelCompania);
        labelCompania.setBounds(20, 60, 80, 30);

        btnSalvar.setBackground(new java.awt.Color(2, 126, 96));
        btnSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(236, 240, 241));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });
        getContentPane().add(btnSalvar);
        btnSalvar.setBounds(190, 230, 100, 30);

        labelItem.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelItem.setText("Item");
        getContentPane().add(labelItem);
        labelItem.setBounds(20, 20, 40, 30);

        jComboBoxCompania.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir Compañia" }));
        jComboBoxCompania.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCompaniaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxCompania);
        jComboBoxCompania.setBounds(140, 60, 150, 30);

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir tipo" }));
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxTipo);
        jComboBoxTipo.setBounds(140, 140, 150, 30);

        labelPrecioPieza.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelPrecioPieza.setText("Precio/Pieza");
        getContentPane().add(labelPrecioPieza);
        labelPrecioPieza.setBounds(20, 100, 90, 30);

        jTxtPrecioPieza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPrecioPiezaActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtPrecioPieza);
        jTxtPrecioPieza.setBounds(140, 100, 150, 30);

        labelCantidad.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelCantidad.setText("Cantidad");
        getContentPane().add(labelCantidad);
        labelCantidad.setBounds(20, 180, 70, 30);

        jTxtCantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCantidadActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtCantidad);
        jTxtCantidad.setBounds(140, 180, 150, 30);

        labelTipo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        labelTipo.setText("Tipo");
        getContentPane().add(labelTipo);
        labelTipo.setBounds(20, 140, 40, 30);

        setBounds(0, 0, 318, 307);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtItemActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
       String path="jdbc:mysql://localhost/";
       String place="ulacitProyecto";
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection myconnection= DriverManager.getConnection(path+place,"root","");
           try
           {
               String q="INSERT INTO productos VALUES(?,?,?,?,?)";
               PreparedStatement mystatement =myconnection.prepareStatement(q);
               
               
               mystatement.setString(1, jTxtItem.getText());
               mystatement.setString(3, jComboBoxCompania.getSelectedItem().toString());
               mystatement.setString(4, jComboBoxTipo.getSelectedItem().toString());
               mystatement.setString(2, jTxtPrecioPieza.getText());
               mystatement.setString(5, jTxtCantidad.getText());
               
               
               mystatement.execute();
           //    label.setText("Saved Succesfully");
              JOptionPane.showMessageDialog(rootPane, "Guardado exitoso");
              jTxtItem.setText(null);
              jTxtPrecioPieza.setText(null);
              jTxtCantidad.setText(null);
              
               mystatement.close();
               myconnection.close();
               
           }
           catch(Exception ae)
           {
             JOptionPane.showMessageDialog(rootPane,"Error en consulta" + ae.getMessage());
           }
       }
       catch(Exception ae)
               {
                 JOptionPane.showMessageDialog(rootPane,"Error en conexión" + ae.getMessage());  
               }

    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jComboBoxCompaniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCompaniaActionPerformed
String path="jdbc:mysql://localhost/";
       String place="ulacitProyecto";
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection myconnection= DriverManager.getConnection(path+place,"root","");
           
           try
           {
               String q="SELECT subcategoria FROM categoria WHERE categoria1=?";
               PreparedStatement mystatement =myconnection.prepareStatement(q);
               mystatement.setString(1, jComboBoxCompania.getSelectedItem().toString());
               ResultSet myresult=mystatement.executeQuery();
               jComboBoxTipo.removeAllItems();
               if(myresult.next())
               {
                   jComboBoxTipo.addItem("Elegir tamaño");
                   do
                   {
                       jComboBoxTipo.addItem(myresult.getString("subcategoria"));
                   }
                   while(myresult.next());
               }
                mystatement.close();
               myconnection.close();
               
           }
           catch(Exception ae)
           {
             JOptionPane.showMessageDialog(rootPane,"Resultado no encontrado");
           }
       }
       catch(Exception ae)
               {
                 JOptionPane.showMessageDialog(rootPane,"Error en conexión" + ae.getMessage());  
               }          // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxCompaniaActionPerformed

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
 String path="jdbc:mysql://localhost/";
       String place="ulacitProyecto";
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection myconnection= DriverManager.getConnection(path+place,"root","");
           try
           {
               String q="SELECT * FROM compania";
               PreparedStatement mystatement =myconnection.prepareStatement(q);
               ResultSet myresult=mystatement.executeQuery();
               if(myresult.next())
               {
                do
                {
                    jComboBoxCompania.addItem(myresult.getString("compania"));
                }
                while(myresult.next());
               }
                mystatement.close();
               myconnection.close();
               
           }
           catch(Exception ae)
           {
             JOptionPane.showMessageDialog(rootPane,"No existen registros");
           }
       }
       catch(Exception ae)
               {
                 JOptionPane.showMessageDialog(rootPane,"Error en conexión" + ae.getMessage());  
               }        
          
    }//GEN-LAST:event_formInternalFrameActivated

    private void jTxtPrecioPiezaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPrecioPiezaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtPrecioPiezaActionPerformed

    private void jTxtCantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCantidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCantidadActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox jComboBoxCompania;
    private javax.swing.JComboBox jComboBoxTipo;
    private javax.swing.JTextField jTxtCantidad;
    private javax.swing.JTextField jTxtItem;
    private javax.swing.JTextField jTxtPrecioPieza;
    private javax.swing.JLabel labelCantidad;
    private javax.swing.JLabel labelCompania;
    private javax.swing.JLabel labelItem;
    private javax.swing.JLabel labelPrecioPieza;
    private javax.swing.JLabel labelTipo;
    // End of variables declaration//GEN-END:variables
}
