/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoConcurrente;
import java.sql.*;
import javax.swing.JOptionPane;


public class Cuenta1 extends javax.swing.JInternalFrame {

    public Cuenta1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelContrasenia = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jTxtNombre = new javax.swing.JTextField();
        jTxtContrasenia = new javax.swing.JPasswordField();
        btnCrearCuenta = new javax.swing.JButton();
        jLabelTipoUsuario = new javax.swing.JLabel();
        postbox = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Agregar Cuenta");
        getContentPane().setLayout(null);

        jLabelContrasenia.setText("Contraseña");
        getContentPane().add(jLabelContrasenia);
        jLabelContrasenia.setBounds(50, 230, 80, 30);

        jLabelUsuario.setText("Usuario");
        getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(50, 90, 80, 30);

        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(50, 190, 80, 30);

        jTxtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtUsuario);
        jTxtUsuario.setBounds(160, 90, 150, 30);

        jTxtNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtNombre);
        jTxtNombre.setBounds(160, 190, 150, 30);

        jTxtContrasenia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtContraseniaActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtContrasenia);
        jTxtContrasenia.setBounds(160, 230, 150, 30);

        btnCrearCuenta.setBackground(new java.awt.Color(2, 126, 96));
        btnCrearCuenta.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnCrearCuenta.setForeground(new java.awt.Color(236, 240, 241));
        btnCrearCuenta.setText("Crear Cuenta");
        btnCrearCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearCuentaActionPerformed(evt);
            }
        });
        getContentPane().add(btnCrearCuenta);
        btnCrearCuenta.setBounds(160, 280, 150, 30);

        jLabelTipoUsuario.setText("Tipo Usuario");
        getContentPane().add(jLabelTipoUsuario);
        jLabelTipoUsuario.setBounds(50, 140, 80, 30);

        postbox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir Puesto", "Administrador", "Vendedor" }));
        postbox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postboxActionPerformed(evt);
            }
        });
        getContentPane().add(postbox);
        postbox.setBounds(160, 140, 150, 30);

        jPanel1.setBackground(new java.awt.Color(2, 126, 96));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(236, 240, 241));
        jLabel6.setText("Crear Cuentas del Sistema");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 380, 70);

        setBounds(0, 0, 381, 371);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtUsuarioActionPerformed

    private void jTxtNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNombreActionPerformed

    private void jTxtContraseniaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtContraseniaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtContraseniaActionPerformed

    private void btnCrearCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearCuentaActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "ulacitProyecto";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "INSERT INTO crearUsuario VALUES(?,?,?,?)";
                PreparedStatement mystatement = myconnection.prepareStatement(q);

                mystatement.setString(1, jTxtUsuario.getText());
                mystatement.setString(2, postbox.getSelectedItem().toString());
                mystatement.setString(3, jTxtNombre.getText());
                mystatement.setString(4, jTxtContrasenia.getText());

                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Cuenta creada exitosamente");
                jTxtUsuario.setText(null);
                jTxtNombre.setText(null);
                jTxtContrasenia.setText(null);
                postbox.setSelectedIndex(0);
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error en consulta" + ae.getMessage());
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error en conexión" + ae.getMessage());
        }
    }//GEN-LAST:event_btnCrearCuentaActionPerformed

    private void postboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postboxActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCrearCuenta;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabelContrasenia;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jTxtContrasenia;
    private javax.swing.JTextField jTxtNombre;
    private javax.swing.JTextField jTxtUsuario;
    private javax.swing.JComboBox postbox;
    // End of variables declaration//GEN-END:variables
}
