/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoConcurrente;

import java.sql.*;
import java.sql.DriverManager;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class EditarPagina extends javax.swing.JInternalFrame {

    public EditarPagina() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabelDireccion = new javax.swing.JLabel();
        jLabelTelefono = new javax.swing.JLabel();
        jLabelPuesto = new javax.swing.JLabel();
        jLabelNumeroID = new javax.swing.JLabel();
        jLabelNombre = new javax.swing.JLabel();
        namebox = new javax.swing.JTextField();
        jComboBoxPuesto = new javax.swing.JComboBox();
        jTxtTelefono = new javax.swing.JFormattedTextField();
        boxMasculino = new javax.swing.JRadioButton();
        boxFemenino = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        addressbox = new javax.swing.JTextArea();
        jLabelGenero = new javax.swing.JLabel();
        jLabelFecNacimiento = new javax.swing.JLabel();
        jComboBoxFechNacDia = new javax.swing.JComboBox();
        jComboBoxFechNacMes = new javax.swing.JComboBox();
        jComboBoxFechNacAnio = new javax.swing.JComboBox();
        btnBuscarNombre = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnBuscarNumeroID = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        idbox = new javax.swing.JTextField();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Editar Empleado");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jLabelDireccion.setText("Dirección");
        getContentPane().add(jLabelDireccion);
        jLabelDireccion.setBounds(60, 160, 80, 30);

        jLabelTelefono.setText("Número Teléfono");
        getContentPane().add(jLabelTelefono);
        jLabelTelefono.setBounds(520, 70, 110, 30);

        jLabelPuesto.setText("Puesto");
        getContentPane().add(jLabelPuesto);
        jLabelPuesto.setBounds(520, 30, 60, 30);

        jLabelNumeroID.setText("Número ID");
        getContentPane().add(jLabelNumeroID);
        jLabelNumeroID.setBounds(60, 30, 70, 30);

        jLabelNombre.setText("Nombre");
        getContentPane().add(jLabelNombre);
        jLabelNombre.setBounds(60, 70, 60, 30);
        getContentPane().add(namebox);
        namebox.setBounds(150, 70, 200, 30);

        jComboBoxPuesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir Puesto", "Gerente", "Supervisor", "Encargado", "Empleado", "Asistente", "Guardia Seguridad" }));
        jComboBoxPuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPuestoActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxPuesto);
        jComboBoxPuesto.setBounds(650, 30, 200, 30);

        try {
            jTxtTelefono.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##########")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jTxtTelefono);
        jTxtTelefono.setBounds(650, 70, 200, 30);

        buttonGroup1.add(boxMasculino);
        boxMasculino.setText("Masculino");
        boxMasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxMasculinoActionPerformed(evt);
            }
        });
        getContentPane().add(boxMasculino);
        boxMasculino.setBounds(150, 120, 100, 28);

        buttonGroup1.add(boxFemenino);
        boxFemenino.setText("Femenino");
        getContentPane().add(boxFemenino);
        boxFemenino.setBounds(260, 120, 110, 28);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        addressbox.setColumns(20);
        addressbox.setRows(5);
        jScrollPane1.setViewportView(addressbox);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(150, 170, 330, 100);

        jLabelGenero.setText("Género");
        getContentPane().add(jLabelGenero);
        jLabelGenero.setBounds(60, 120, 70, 30);

        jLabelFecNacimiento.setText("Fecha de Nacimiento");
        getContentPane().add(jLabelFecNacimiento);
        jLabelFecNacimiento.setBounds(520, 120, 130, 30);

        jComboBoxFechNacDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Día" }));
        jComboBoxFechNacDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFechNacDiaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxFechNacDia);
        jComboBoxFechNacDia.setBounds(650, 120, 60, 30);

        jComboBoxFechNacMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes" }));
        getContentPane().add(jComboBoxFechNacMes);
        jComboBoxFechNacMes.setBounds(710, 120, 70, 30);

        jComboBoxFechNacAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año" }));
        jComboBoxFechNacAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxFechNacAnioActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxFechNacAnio);
        jComboBoxFechNacAnio.setBounds(780, 120, 70, 30);

        btnBuscarNombre.setBackground(new java.awt.Color(2, 126, 96));
        btnBuscarNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarNombre.setForeground(new java.awt.Color(236, 240, 241));
        btnBuscarNombre.setText("Buscar");
        btnBuscarNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNombreActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarNombre);
        btnBuscarNombre.setBounds(370, 70, 110, 30);

        btnActualizar.setBackground(new java.awt.Color(2, 126, 96));
        btnActualizar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnActualizar.setForeground(new java.awt.Color(236, 240, 241));
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnActualizar);
        btnActualizar.setBounds(580, 190, 100, 60);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Teléfono", "Género", "Dirección", "Fecha de Nacimiento", "Direccion"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTable1);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(30, 290, 860, 180);

        btnBuscarNumeroID.setBackground(new java.awt.Color(2, 126, 96));
        btnBuscarNumeroID.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscarNumeroID.setForeground(new java.awt.Color(236, 240, 241));
        btnBuscarNumeroID.setText("Buscar");
        btnBuscarNumeroID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarNumeroIDActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscarNumeroID);
        btnBuscarNumeroID.setBounds(370, 30, 110, 30);

        btnBorrar.setBackground(new java.awt.Color(2, 126, 96));
        btnBorrar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBorrar.setForeground(new java.awt.Color(236, 240, 241));
        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBorrar);
        btnBorrar.setBounds(710, 190, 110, 60);
        getContentPane().add(idbox);
        idbox.setBounds(150, 30, 200, 30);

        setBounds(0, 0, 918, 521);
    }// </editor-fold>//GEN-END:initComponents

    private void boxMasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxMasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxMasculinoActionPerformed
    
    private void jComboBoxPuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPuestoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPuestoActionPerformed
    
    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    }//GEN-LAST:event_formInternalFrameActivated
    
    private void jComboBoxFechNacDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFechNacDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFechNacDiaActionPerformed
    
    private void btnBuscarNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNombreActionPerformed
        
        
        idbox.setText("");
        jTxtTelefono.setText("");
        addressbox.setText("");
        jComboBoxFechNacDia.setSelectedIndex(0);
        jComboBoxFechNacMes.setSelectedIndex(0);
        jComboBoxFechNacAnio.setSelectedIndex(0);
        jComboBoxPuesto.setSelectedIndex(0);
        buttonGroup1.clearSelection();
        
        String path = "jdbc:mysql://localhost/";
        String place = "ulacitProyecto";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            String idMiembro, nombre, telefono, direccion, fechaDeNacimiento, genero, puesto;
            try {
                String q = "SELECT * FROM miembro WHERE NOMBRE like '%" + namebox.getText() + "%'";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                ResultSet myresult = mystatement.executeQuery();
                mymodel.setRowCount(0);
                jScrollPane3.setVisible(true);
                if (myresult.next()) {
                    do {
                        idMiembro = myresult.getString("ID");
                        nombre = myresult.getString("NOMBRE");
                        telefono = myresult.getString("TELEFONO");
                        direccion = myresult.getString("DIRECCION");
                        fechaDeNacimiento = myresult.getString("fechaDeNacimiento");
                        genero = myresult.getString("GENERO");
                        puesto = myresult.getString("tipoUsuario");
                        mymodel.addRow(new Object[]{idMiembro, nombre, telefono, genero, direccion, fechaDeNacimiento, puesto});
                        jScrollPane3.setVisible(true);
                    } while (myresult.next());
                } else {
                    jScrollPane3.setVisible(false);
                    JOptionPane.showMessageDialog(rootPane, "No existen registros");
                }
                mystatement.close();
                myconnection.close();
                
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Miembro no Encontrado");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error en Conexión" + ae.getMessage());
        }
    }//GEN-LAST:event_btnBuscarNombreActionPerformed
    
    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "ulacitProyecto";
        int i = JOptionPane.showConfirmDialog(rootPane, "¿Esta seguro que desea actualizar este empleado?");
        if (i == 0) {
            try {
                Class.forName("com.mysql.jdbc.Driver");
                Connection myconnection = DriverManager.getConnection(path + place, "root", "");
                try {
                    String q = "UPDATE miembro SET NOMBRE=?,TELEFONO=?,DIRECCION=?,GENERO=?,fechaDeNacimiento=?,tipoUsuario=? WHERE ID=?";
                    PreparedStatement mystatement = myconnection.prepareStatement(q);
                    mystatement.setString(1, namebox.getText());
                    mystatement.setString(2, jTxtTelefono.getText());
                    if (boxMasculino.isSelected()) {
                        mystatement.setString(4, "Masculino");
                    } else if (boxFemenino.isSelected()) {
                        mystatement.setString(4, "Femenino");
                    }
                    mystatement.setString(3, addressbox.getText());
                    String dob = jComboBoxFechNacAnio.getSelectedItem() + "-" + jComboBoxFechNacMes.getSelectedItem() + "-" + jComboBoxFechNacDia.getSelectedItem();
                    mystatement.setString(5, dob);
                    mystatement.setString(6, jComboBoxPuesto.getSelectedItem().toString());
                    mystatement.setString(7, idbox.getText());
                    mystatement.execute();
                    JOptionPane.showMessageDialog(rootPane, "Actualización Exitosa");
                    
                    mystatement.close();
                    myconnection.close();
                    
                    namebox.setText("");
                    btnBuscarNombreActionPerformed(null);
                    
                } catch (Exception ae) {
                    JOptionPane.showMessageDialog(rootPane, "Error en Consulta" + ae.getMessage());
                }
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error en Conexión" + ae.getMessage());
            }
        }
        
    }//GEN-LAST:event_btnActualizarActionPerformed
    
    private void jComboBoxFechNacAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxFechNacAnioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxFechNacAnioActionPerformed
    
    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int myrow = jTable1.getSelectedRow();
        
        String data = (String) jTable1.getValueAt(myrow, 0);
        idbox.setText(data);
        btnBuscarNumeroIDActionPerformed(null);
    }//GEN-LAST:event_jTable1MouseClicked
    
    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        jScrollPane3.setVisible(false);
        
        
        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                jComboBoxFechNacDia.addItem("0" + a);
            } else {
                jComboBoxFechNacDia.addItem("" + a);
            }
            
        }
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                jComboBoxFechNacMes.addItem("0" + a);
            } else {
                jComboBoxFechNacMes.addItem("" + a);
            }
            
        }
        for (int a = 1975; a <= 2013; a++) {
            jComboBoxFechNacAnio.addItem("" + a);
        }
        
    }//GEN-LAST:event_formInternalFrameOpened
    
private void btnBuscarNumeroIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarNumeroIDActionPerformed
    String path = "jdbc:mysql://localhost/";
    String place = "ulacitProyecto";
    try {
        Class.forName("com.mysql.jdbc.Driver");
        Connection myconnection = DriverManager.getConnection(path + place, "root", "");
        try {
            String q = "SELECT * FROM miembro WHERE ID=?";
            PreparedStatement mystatement = myconnection.prepareStatement(q);
            mystatement.setString(1, idbox.getText());
            ResultSet myresult = mystatement.executeQuery();
            if (myresult.next()) {
                namebox.setText(myresult.getString("NOMBRE"));
                jTxtTelefono.setText(myresult.getString("TELEFONO"));
                addressbox.setText(myresult.getString("DIRECCION"));
                String db = myresult.getString("fechaDeNacimiento");
                String a[] = db.split("-");
                jComboBoxFechNacDia.setSelectedItem(a[2]);
                jComboBoxFechNacMes.setSelectedItem(a[1]);
                jComboBoxFechNacAnio.setSelectedItem(a[0]);
                if (myresult.getString("GENERO").equals("Masculino")) {
                    boxMasculino.setSelected(true);
                } else if (myresult.getString("GENERO").equals("Femenino")) {
                    boxFemenino.setSelected(true);
                }
                
                String p = myresult.getString("tipoUsuario");
                jComboBoxPuesto.setSelectedItem(p);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Registros NO encontrados", "ERROR", 0);
            }
            mystatement.close();
            myconnection.close();
            
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error en Consulta" + ae.getMessage());
        }
    } catch (Exception ae) {
        JOptionPane.showMessageDialog(rootPane, "Error en Conexión" + ae.getMessage());
    }
}//GEN-LAST:event_btnBuscarNumeroIDActionPerformed
    
private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
    String path = "jdbc:mysql://localhost/";
    String place = "ulacitProyecto";
    
    int i = JOptionPane.showConfirmDialog(rootPane, "¿Está seguro que desea eliminar este empleado? ");
    if (i == 0) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            try {
                String q = "DELETE FROM miembro WHERE ID=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                mystatement.setString(1, idbox.getText());
                int b = mystatement.executeUpdate();
                if (b > 0) {
                    JOptionPane.showMessageDialog(rootPane, "Borrado Exitoso");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Ya ha sido borrado");
                }
                mystatement.close();
                myconnection.close();
                
            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Error en consulta" + ae.getMessage());
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error en conexion" + ae.getMessage());
        }
    }
}//GEN-LAST:event_btnBorrarActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea addressbox;
    private javax.swing.JRadioButton boxFemenino;
    private javax.swing.JRadioButton boxMasculino;
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscarNombre;
    private javax.swing.JButton btnBuscarNumeroID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField idbox;
    private javax.swing.JComboBox jComboBoxFechNacAnio;
    private javax.swing.JComboBox jComboBoxFechNacDia;
    private javax.swing.JComboBox jComboBoxFechNacMes;
    private javax.swing.JComboBox jComboBoxPuesto;
    private javax.swing.JLabel jLabelDireccion;
    private javax.swing.JLabel jLabelFecNacimiento;
    private javax.swing.JLabel jLabelGenero;
    private javax.swing.JLabel jLabelNombre;
    private javax.swing.JLabel jLabelNumeroID;
    private javax.swing.JLabel jLabelPuesto;
    private javax.swing.JLabel jLabelTelefono;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JFormattedTextField jTxtTelefono;
    private javax.swing.JTextField namebox;
    // End of variables declaration//GEN-END:variables
}
