
package ProyectoConcurrente;

import java.sql.*;
import javax.swing.JOptionPane;
public class Tienda extends javax.swing.JInternalFrame {

    public Tienda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jTxtNombreProveedor = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jTxtTituloAgregarProveedor = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Agregar Companía");
        getContentPane().setLayout(null);

        jTxtNombreProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNombreProveedorActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtNombreProveedor);
        jTxtNombreProveedor.setBounds(40, 100, 230, 30);

        btnAgregar.setBackground(new java.awt.Color(2, 126, 96));
        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setForeground(new java.awt.Color(236, 240, 241));
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });
        getContentPane().add(btnAgregar);
        btnAgregar.setBounds(100, 160, 110, 30);

        jPanel1.setBackground(new java.awt.Color(2, 126, 96));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTxtTituloAgregarProveedor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTxtTituloAgregarProveedor.setForeground(new java.awt.Color(236, 240, 241));
        jTxtTituloAgregarProveedor.setText("Agregar Proveedor");
        jPanel1.add(jTxtTituloAgregarProveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 120, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 320, 70);

        setBounds(0, 0, 314, 247);
    }// </editor-fold>//GEN-END:initComponents

    private void jTxtNombreProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNombreProveedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNombreProveedorActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        String path="jdbc:mysql://localhost/";
        String place="ulacitProyecto";
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection= DriverManager.getConnection(path+place,"root","");
            try
            {
                String q="INSERT INTO compania VALUES(?)";
                PreparedStatement mystatement =myconnection.prepareStatement(q);
                mystatement.setString(1, jTxtNombreProveedor.getText());
                mystatement.execute();
                JOptionPane.showMessageDialog(rootPane, "Guardado exitoso");
                jTxtNombreProveedor.setText(null);

                mystatement.close();
                myconnection.close();

            }
            catch(Exception ae)
            {
                JOptionPane.showMessageDialog(rootPane,"Error en consulta" + ae.getMessage());
            }
        }
        catch(Exception ae)
        {
            JOptionPane.showMessageDialog(rootPane,"Error en conexión" + ae.getMessage());
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTxtNombreProveedor;
    private javax.swing.JLabel jTxtTituloAgregarProveedor;
    // End of variables declaration//GEN-END:variables
}
