/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoConcurrente;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VistaFactura1 extends javax.swing.JInternalFrame {

    public VistaFactura1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelSeleccionarFecha = new javax.swing.JLabel();
        jComboBoxDia = new javax.swing.JComboBox();
        jComboBoxMes = new javax.swing.JComboBox();
        jComboBoxAnio = new javax.swing.JComboBox();
        btnBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabelTituloDetalleFacturas = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Ver Factura");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Número Factura", "Nombre Proveedor", "Número Contacto", "Producto", "Cantidad", "Valor Total", "Fecha"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(50, 120, 970, 500);

        jLabelSeleccionarFecha.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSeleccionarFecha.setText("Seleccionar Fecha");
        getContentPane().add(jLabelSeleccionarFecha);
        jLabelSeleccionarFecha.setBounds(50, 80, 110, 30);

        jComboBoxDia.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxDia.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Día" }));
        jComboBoxDia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxDiaActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBoxDia);
        jComboBoxDia.setBounds(170, 80, 60, 30);

        jComboBoxMes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Mes" }));
        getContentPane().add(jComboBoxMes);
        jComboBoxMes.setBounds(230, 80, 70, 30);

        jComboBoxAnio.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jComboBoxAnio.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Año" }));
        getContentPane().add(jComboBoxAnio);
        jComboBoxAnio.setBounds(300, 80, 70, 30);

        btnBuscar.setBackground(new java.awt.Color(2, 126, 96));
        btnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });
        getContentPane().add(btnBuscar);
        btnBuscar.setBounds(390, 80, 100, 31);

        jPanel1.setBackground(new java.awt.Color(2, 126, 96));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloDetalleFacturas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTituloDetalleFacturas.setForeground(new java.awt.Color(236, 240, 241));
        jLabelTituloDetalleFacturas.setText("Detalles de Factura");
        jPanel1.add(jLabelTituloDetalleFacturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 120, 20));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1070, 60);

        setBounds(0, 0, 1065, 658);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
    }//GEN-LAST:event_formInternalFrameActivated

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened

        for (int a = 1; a <= 31; a++) {
            if (a < 10) {
                jComboBoxDia.addItem("0" + a);
            } else {
                jComboBoxDia.addItem(String.valueOf(a));
            }
        }
        
        for (int a = 1; a <= 12; a++) {
            if (a < 10) {
                jComboBoxMes.addItem("0" + a);
            } else {
                jComboBoxMes.addItem(String.valueOf(a));
            }
        }
        
        for (int a = 2013; a <= 2113; a++) {
            jComboBoxAnio.addItem(String.valueOf(a));
        }
    }//GEN-LAST:event_formInternalFrameOpened

    private void jComboBoxDiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxDiaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxDiaActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String path = "jdbc:mysql://localhost/";
        String place = "ulacitProyecto";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");
            String idFactura, proveedor, telefono, productos, cantidad, total, fecha;
            try {
                String q = "SELECT * FROM factura WHERE fecha=?";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                DefaultTableModel mymodel = (DefaultTableModel) jTable1.getModel();
                mystatement.setString(1, jComboBoxAnio.getSelectedItem().toString() + "-" + jComboBoxMes.getSelectedItem().toString() + "-" + jComboBoxDia.getSelectedItem().toString());
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    do {
                        idFactura = myresult.getString("idFactura");
                        proveedor = myresult.getString("proveedor");
                        telefono = myresult.getString("telefono");
                        productos = myresult.getString("productos");
                        //     String p[]=product.split(",");
                        //   for(int i=0;i<10;i++)
                        //{
                            //       product=myresult.getString("products");
                            //    String p[]=product.split(",");
                            //    product=(p[i]+"\n");
                        //}
                        productos = myresult.getString("productos");
                        cantidad = myresult.getString("cantidad");
                        total = myresult.getString("total");
                        fecha = myresult.getString("date");
                        String a[] = fecha.split("-");
                        fecha = (a[2] + "-" + a[1] + "-" + a[0]);
                        mymodel.addRow(new Object[]{idFactura, proveedor, telefono, productos, cantidad, total, fecha});
                    } while (myresult.next());
                }
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "No existen registros");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error en conexión" + ae.getMessage());
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBuscarActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JComboBox jComboBoxAnio;
    private javax.swing.JComboBox jComboBoxDia;
    private javax.swing.JComboBox jComboBoxMes;
    private javax.swing.JLabel jLabelSeleccionarFecha;
    private javax.swing.JLabel jLabelTituloDetalleFacturas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
