/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ProyectoConcurrente;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VistaEmpleado1 extends javax.swing.JInternalFrame {

    public VistaEmpleado1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        jLabelTituloDetallesEmpleado = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("Vista de Empleado");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(null);

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Teléfono", "Género", "Dirección", "Fecha de Nacimiento", "Id", "Puesto"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 140, 970, 480);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Por Puesto");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 90, 90, 30);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Elegir Puesto", "Supervisor", "Encargado", "Empleados", "Asistente", "Guardia de Seguridad" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(130, 90, 150, 30);

        jPanel1.setBackground(new java.awt.Color(2, 126, 96));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelTituloDetallesEmpleado.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTituloDetallesEmpleado.setForeground(new java.awt.Color(236, 240, 241));
        jLabelTituloDetallesEmpleado.setText("Detalles de Empleado");
        jPanel1.add(jLabelTituloDetallesEmpleado, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 30, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1060, 70);

        setBounds(0, 0, 1061, 667);
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        String path = "jdbc:mysql://localhost/";
        String place = "ulacitProyecto";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Connection myconnection = DriverManager.getConnection(path + place, "root", "");

            try {
                String q = "SELECT tipoUsuario FROM miembro";
                PreparedStatement mystatement = myconnection.prepareStatement(q);
                ResultSet myresult = mystatement.executeQuery();
                if (myresult.next()) {
                    jComboBox1.removeItem("Supervisor");
                    jComboBox1.addItem(myresult.getString("tipoUsuario"));
                }
                mystatement.close();
                myconnection.close();

            } catch (Exception ae) {
                JOptionPane.showMessageDialog(rootPane, "Resultado no encontrado");
            }
        } catch (Exception ae) {
            JOptionPane.showMessageDialog(rootPane, "Error en conexión" + ae.getMessage());
        }          // TODO add your handling code here:

    }//GEN-LAST:event_formInternalFrameActivated

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
   String path="jdbc:mysql://localhost/";
       String place="ulacitProyecto";
       try
       {
           Class.forName("com.mysql.jdbc.Driver");
           Connection myconnection= DriverManager.getConnection(path+place,"root","");
           String memberid,name,phone,address,dob,gender,post;
           try
           {
               String q="SELECT * FROM miembro WHERE tipoUsuario=?";
               PreparedStatement mystatement =myconnection.prepareStatement(q);
               mystatement.setString(1, jComboBox1.getSelectedItem().toString());
               DefaultTableModel mymodel=(DefaultTableModel) jTable1.getModel();
               ResultSet myresult=mystatement.executeQuery();
               mymodel.setRowCount(0);
               if(myresult.next())
               {
                do
                {
                    memberid=myresult.getString("ID");
                    name=myresult.getString("NOMBRE");
                    phone=myresult.getString("TELEFONO");
                    address=myresult.getString("DIRECCION");
                    dob=myresult.getString("fechaDeNacimiento");
                    gender=myresult.getString("GENERO");
                    post=myresult.getString("tipoUsuario");
                    mymodel.addRow(new Object[]{name,phone,gender,address,dob,memberid,post});
                }
                while(myresult.next());
               }
                mystatement.close();
               myconnection.close();
               
           }
           catch(Exception ae)
           {
             JOptionPane.showMessageDialog(rootPane,"No existen registros");
           }
       }
       catch(Exception ae)
               {
                 JOptionPane.showMessageDialog(rootPane,"Error en conexión" + ae.getMessage());  
               }        
             // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelTituloDetallesEmpleado;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
