//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDescargas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class consecutivo
    {
        public int id { get; set; }
        public string descripcion { get; set; }
        public int consecutivo1 { get; set; }
        public bool permite_prefijo { get; set; }
        public string prefijo { get; set; }
        public Nullable<bool> rango { get; set; }
        public Nullable<int> init_rango { get; set; }
        public Nullable<int> end_rango { get; set; }
    }
}
