//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDescargas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class easy_pay
    {
        public int id { get; set; }
        public int num_cuenta { get; set; }
        public int codigo_seguridad { get; set; }
        public string contrasenia { get; set; }
        public string id_tarjeta { get; set; }
    }
}
