//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDescargas.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class eDescargasEntities : DbContext
    {
        public eDescargasEntities()
            : base("name=eDescargasEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bitacora> bitacoras { get; set; }
        public virtual DbSet<consecutivo> consecutivos { get; set; }
        public virtual DbSet<descarga> descargas { get; set; }
        public virtual DbSet<easy_pay> easy_pay { get; set; }
        public virtual DbSet<errore> errores { get; set; }
        public virtual DbSet<genero> generos { get; set; }
        public virtual DbSet<idioma> idiomas { get; set; }
        public virtual DbSet<libro> libros { get; set; }
        public virtual DbSet<musica> musicas { get; set; }
        public virtual DbSet<pais> paises { get; set; }
        public virtual DbSet<parametro> parametros { get; set; }
        public virtual DbSet<pelicula> peliculas { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tarjeta> tarjetas { get; set; }
        public virtual DbSet<transaccione> transacciones { get; set; }
        public virtual DbSet<usuario> usuarios { get; set; }
        public virtual DbSet<usuarios_roles> usuarios_roles { get; set; }
    }
}
