//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDescargas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class errore
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public string mensaje { get; set; }
        public Nullable<int> numero_error { get; set; }
    }
}
