//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDescargas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class musica
    {
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_genero { get; set; }
        public string tipo_interprete { get; set; }
        public int id_idioma { get; set; }
        public int id_pais { get; set; }
        public string disquera { get; set; }
        public string nombre_disco { get; set; }
        public int anio { get; set; }
        public string archivo_descarga { get; set; }
        public string archivo_preview { get; set; }
        public int cantidad_descarga { get; set; }
        public string consecutivo { get; set; }
        public int precio { get; set; }
    
        public virtual genero genero { get; set; }
        public virtual idioma idioma { get; set; }
        public virtual pais pais { get; set; }
    }
}
