//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDescargas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametro
    {
        public int id { get; set; }
        public string preview_libros { get; set; }
        public string path_libros { get; set; }
        public string preview_musica { get; set; }
        public string path_musica { get; set; }
        public string preview_peliculas { get; set; }
        public string path_peliculas { get; set; }
    }
}
