//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eDescargas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios_roles
    {
        public string id { get; set; }
        public int id_usuario { get; set; }
        public int id_rol { get; set; }
    
        public virtual role role { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
